### ISSUE TITLE
downloadFile() InteropClientImpl bug

### ISSUE THREAD

**Issue by scorobogaci** [jasonwjones/pbj-pbcs-client#1]
return null ;

**Comment by jasonwjones** [comment]
Thanks -- the code for the exists and is written but just isn't synced to master. I just have a few cleanup things to do on it and test but should have the latest code synced today or tomorrow.

**Comment by scorobogaci** [comment]
alright man , let me know if I can help you with something

**Comment by scorobogaci** [comment]
Do you plan to release a new version ?
current is : `<version>1.0.1</version>`

**Comment by scorobogaci** [comment]
uploadFile()
addMember()
from PbcsApplication and PbcsClient have also bugs, or are not finished yet :(
I guess, this library does not have a stable-tested version ?

**Comment by jasonwjones** [comment]
File upload and download should be fixed now. I also made a few other adjustments that should make things easier for Java 1.6 and integrating with FDMEE. Please note on the addMember() function that it's technically implemented but returns null right now. It's experimental at the moment. It doesn't actually add an arbitrary member to an outline, it is meant to work with the dynamic naming feature that you can enable in Planning. This is something I haven't worked with and could actually use some help testing, in case you are able to work with it

**Comment by jasonwjones** [comment]
Closing this issue for now -- I created a new issue to track the addMember() functionality. Again, it technically makes the call to the REST API but just returns null. So if you are able to test it and see that a change actually happened on the outline (using a dimension with dynamic names enabled) and provide feedback that'd be very helpful
